import { Injectable, UnauthorizedException } from '@nestjs/common';
import { UserRepository } from './repository/user.repository';
import { AuthCreadentialDto } from './dto/auth.credential.dto';
import { UserCredentialDto } from './dto/user.credential.dto';
import * as bcrypt from 'bcryptjs';
import { DataSource, Entity, Repository } from 'typeorm';
import { User } from 'src/entities/user.entity';

@Injectable()
export class AuthService {
    constructor(
        private dataSource: DataSource,
        private userRepository: UserRepository,
    ) { }

    async signUp(authCredentialDto: AuthCreadentialDto): Promise<void> {
        await this.userRepository.createUser(authCredentialDto);
    }

    async signIn(userCredentialDto: UserCredentialDto): Promise<User> {
        // Make sign and match with company name and Make companyName to Unique parameter
        const { userName, password } = userCredentialDto;
        const user = await this.userRepository.findOne({ where: { userName: userName } });

        if(user && ( await bcrypt.compare(password, user.password))) {
            // User token generated by ( Secret + Payload )
            return user;
        }else{
            throw new UnauthorizedException();
        }
    }
}
